language: node_js
node_js:
  - "4.5"
script:
  - npm install -g bower firebase-tools polymer-cli
  - bower install
  - polymer build
  - polymer test
after_success:
  - chmod +x deploy.sh
cache:
  directories:
    - bower_components
deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master